### ISSUE TITLE
undefined method `_routes' for Puffer::BaseCell:Class

### ISSUE THREAD

**Issue by undr** [puffer/puffer#1]
Создал контроллер User, командой:

```
rails g puffer:controller User
```

в routes.rb добавил:

```
constraints(:subdomain => "admin") do
  scope :module => "admin" do
    scope :as => "admin" do
      resources :users
    end
  end
end
```

При запросе http://admin.lvh.me:3000/users происходит ошибка:

```
Showing /Users/undr/.rvm/gems/ruby-1.8.7-p174/gems/puffer-0.0.12/app/views/layouts/puffer.html.erb where line 33 raised:

undefined method `_routes' for Puffer::BaseCell:Class

Extracted source (around line 33):

30:               <% sidebar_puffer_navigation do |title, path, current| %>
31:                 <li<%= raw(current ? ' class="selected"' : '') %>>
32:                   <%= link_to title, path %>
33:                   <% if current && (additional = render_cell('puffer/base', 'additional')).present? %>
34:                     <div class="additional">
35:                       <%= additional %>
36:                     </div>
```

Rails 3.0.3
Ruby 1.8.7-p174
postgresql

Как с этим бороться?

**Comment by pyromaniac** [comment]
Хм. Вообще, я не пробовал делать админку под сабдоменом. Пока только в неймспейсе. Я обязательно протестирую в ближайшее время и сообщу. Спасибо за репорт.

**Comment by pyromaniac** [comment]
Что-то не нашёл бага по этому адресу. Всё работает, кажется. Сами починили? Или с обновлением проблема пропала?

**Comment by undr** [comment]
По какому адресу? По admin.lvh.me? Это синоним localhost. То есть бага у меня на домашней машине. Нет сам я пока не починил, уезжал. Сейчас попробую сам разобраться, если что узнаю - напишу.

**Comment by pyromaniac** [comment]
А блин, старый я наркоман. Кароче, у себя попытался воспроизвести - не вышло. Работает. Может, дополнительные сведения действительно есть? Фулл стек-трейс, например.

**Comment by undr** [comment]
```
cells (3.4.4) lib/cell/rails.rb:68:in `view_context_class'
cells (3.4.4) lib/cell/rails.rb:66:in `class_eval'
cells (3.4.4) lib/cell/rails.rb:66:in `view_context_class'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:68:in `view_context_class'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:86:in `view_context'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:114:in `_render_template'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:108:in `render_to_body'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:101:in `render_to_string'
cells (3.4.4) lib/cell/rails.rb:159:in `render_view_for'
cells (3.4.4) lib/cell/rails.rb:124:in `render'
puffer (0.0.12) app/cells/puffer/base_cell.rb:11:in `additional'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/base.rb:151:in `send_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/base.rb:151:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/callbacks.rb:18:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:430:in `_run__5388930__process_action__24015689__callbacks'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:409:in `send'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:409:in `_run_process_action_callbacks'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:93:in `send'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:93:in `run_callbacks'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/callbacks.rb:17:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/base.rb:120:in `process'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:40:in `process'
cells (3.4.4) lib/cell/rails.rb:32:in `render_state'
cells (3.4.4) lib/cell/caching.rb:95:in `render_state'
cells (3.4.4) lib/cell.rb:10:in `render_cell_for'
cells (3.4.4) lib/cells/rails.rb:49:in `render_cell'
puffer (0.0.12) app/views/layouts/puffer.html.erb:33:in `___sers_undr__rvm_gems_ruby_______p____gems_puffer________app_views_layouts_puffer_html_erb__270449741_30707070_0'
puffer (0.0.12) lib/puffer/controller/helpers.rb:42:in `sidebar_puffer_navigation'
puffer (0.0.12) lib/puffer/controller/helpers.rb:38:in `each'
puffer (0.0.12) lib/puffer/controller/helpers.rb:38:in `sidebar_puffer_navigation'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/helpers.rb:55:in `send'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/helpers.rb:55:in `sidebar_puffer_navigation'
puffer (0.0.12) app/views/layouts/puffer.html.erb:30:in `___sers_undr__rvm_gems_ruby_______p____gems_puffer________app_views_layouts_puffer_html_erb__270449741_30707070_0'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_view/template.rb:135:in `send'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_view/template.rb:135:in `render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/notifications.rb:54:in `instrument'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_view/template.rb:127:in `render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_view/render/layouts.rb:80:in `_render_layout'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_view/render/rendering.rb:62:in `_render_template'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/notifications.rb:52:in `instrument'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/notifications.rb:52:in `instrument'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_view/render/rendering.rb:56:in `_render_template'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_view/render/rendering.rb:26:in `render_without_haml'
haml (3.0.25) lib/haml/helpers/action_view_mods.rb:13:in `render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:114:in `_render_template'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:108:in `render_to_body'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/renderers.rb:47:in `render_to_body'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/compatibility.rb:55:in `render_to_body'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:101:in `render_to_string'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:92:in `render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/rendering.rb:17:in `render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/instrumentation.rb:40:in `render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/core_ext/benchmark.rb:5:in `ms'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/core_ext/benchmark.rb:5:in `ms'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/instrumentation.rb:40:in `render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/instrumentation.rb:78:in `cleanup_view_runtime'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activerecord/lib/active_record/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/thinking-sphinx-a3c10330a5cd/lib/thinking_sphinx/action_controller.rb:12:in `cleanup_view_runtime'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/instrumentation.rb:39:in `render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/base.rb:151:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/rendering.rb:11:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/callbacks.rb:18:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:440:in `_run__248458308__process_action__199225275__callbacks'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:409:in `send'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:409:in `_run_process_action_callbacks'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:93:in `send'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:93:in `run_callbacks'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/callbacks.rb:17:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/notifications.rb:52:in `instrument'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/notifications.rb:52:in `instrument'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/rescue.rb:17:in `process_action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/base.rb:120:in `process'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/abstract_controller/rendering.rb:40:in `process'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal.rb:138:in `dispatch'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_controller/metal.rb:178:in `action'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/routing/route_set.rb:62:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/routing/route_set.rb:27:in `call'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:148:in `call'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:93:in `recognize'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:138:in `optimized_each'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:92:in `recognize'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:139:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/routing/route_set.rb:492:in `call'
sass (3.1.0.alpha.206) lib/sass/./sass/plugin/rack.rb:54:in `call'
warden (1.0.3) lib/warden/manager.rb:35:in `call'
warden (1.0.3) lib/warden/manager.rb:34:in `catch'
warden (1.0.3) lib/warden/manager.rb:34:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/head.rb:14:in `call'
rack (1.2.1) lib/rack/methodoverride.rb:24:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/flash.rb:182:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/cookies.rb:295:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activerecord/lib/active_record/query_cache.rb:32:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activerecord/lib/active_record/query_cache.rb:12:in `cache'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activerecord/lib/active_record/query_cache.rb:31:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:353:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/callbacks.rb:46:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/callbacks.rb:415:in `_run_call_callbacks'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/callbacks.rb:44:in `call'
rack (1.2.1) lib/rack/sendfile.rb:107:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:46:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/rack/logger.rb:13:in `call'
rack (1.2.1) lib/rack/runtime.rb:17:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/activesupport/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.2.1) lib/rack/lock.rb:11:in `call'
rack (1.2.1) lib/rack/lock.rb:11:in `synchronize'
rack (1.2.1) lib/rack/lock.rb:11:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/actionpack/lib/action_dispatch/middleware/static.rb:30:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/application.rb:168:in `call'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/application.rb:77:in `send'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/application.rb:77:in `method_missing'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.2.1) lib/rack/content_length.rb:13:in `call'
rack (1.2.1) lib/rack/handler/webrick.rb:52:in `service'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/server.rb:162:in `start'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/server.rb:95:in `start'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/server.rb:92:in `each'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/server.rb:92:in `start'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/server.rb:23:in `start'
/Users/undr/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/webrick/server.rb:82:in `start'
rack (1.2.1) lib/rack/handler/webrick.rb:13:in `run'
rack (1.2.1) lib/rack/server.rb:213:in `start'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/commands/server.rb:65:in `start'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/commands.rb:30
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/commands.rb:27:in `tap'
/Users/undr/.rvm/gems/ruby-1.8.7-p174/bundler/gems/rails-0adfe35f1f8e/railties/lib/rails/commands.rb:27
script/rails:6:in `require'
script/rails:6
```

rails-0adfe35f1f8e - это rails 3.0.3 + https://github.com/undr/rails/commit/0adfe35f1f8eb98422a4ccc1947663900a089d02

Возможно у меня стоят какие-нибудь специфические гемы. Завтра я посмотрю что к чему, сегодня уже поздновато.

**Comment by pyromaniac** [comment]
Ага, и ещё стоит обновить cells. Похоже, что не в пуффере дело. А если и в нём, то опосредованно. Кажется, с контроллером я там ничего не делаю таки.
